import { readFile, writeFile, mkdir, rm, symlink, link, copyFile } from 'fs/promises';
import glob from 'fast-glob';
import path from 'path';

// Run all three pre-build stages. Returns the list of discovered latex packages.
export async function stage(config) {
  const packages = await findLatexPackages(config.configDir);
  await populateTexmf(config.tex4npmTexmf, packages);
  await generateBundleEntry(config.tex4npmDir, packages);
  return packages;
}

// Stage 1: scan node_modules for packages with a "latex" field.
// Only checks top-level and scoped packages, not deeply nested ones.
export async function findLatexPackages(root) {
  const manifests = await glob(
    ['node_modules/*/package.json', 'node_modules/@*/*/package.json'],
    { cwd: root, absolute: true }
  );

  const packages = [];
  for (const manifestPath of manifests) {
    let pkg;
    try {
      pkg = JSON.parse(await readFile(manifestPath, 'utf8'));
    } catch {
      continue;
    }
    if (!pkg.latex) continue;
    // "postprocess" may be a single relative path or an array; normalize to array.
    // Modules are loaded and executed by postprocess.js (Phase 4, D5).
    const rawPost = pkg.latex.postprocess;
    const postprocess = Array.isArray(rawPost) ? rawPost : (rawPost ? [rawPost] : []);
    packages.push({
      name: pkg.name,
      dir: path.dirname(manifestPath),
      sty: pkg.latex.sty ?? [],
      css: pkg.latex.css ?? [],
      postprocess,
    });
  }

  return packages;
}

// Stage 2: wipe .tex4npm/texmf/tex/latex/ and repopulate with links to .sty files.
// Throws on filename collision between two packages.
export async function populateTexmf(tex4npmTexmf, packages) {
  const latexDir = path.join(tex4npmTexmf, 'tex', 'latex');
  await rm(latexDir, { recursive: true, force: true });
  await mkdir(latexDir, { recursive: true });

  const seen = new Map(); // basename → package name

  for (const pkg of packages) {
    for (const styRel of pkg.sty) {
      const src = path.resolve(pkg.dir, styRel);
      const basename = path.basename(styRel);

      if (seen.has(basename)) {
        throw new Error(
          `.sty filename collision: ${basename} is declared by both ` +
          `${seen.get(basename)} and ${pkg.name}`
        );
      }
      seen.set(basename, pkg.name);

      await linkWithFallback(src, path.join(latexDir, basename));
    }
  }
}

// Stage 3: write .tex4npm/bundle-entry.js importing all ximera package JS and CSS.
export async function generateBundleEntry(tex4npmDir, packages) {
  await mkdir(tex4npmDir, { recursive: true });

  const jsImports = packages.map(p => `import ${JSON.stringify(p.name)};`);
  const cssImports = packages.flatMap(p =>
    p.css.map(rel => `import ${JSON.stringify(p.name + '/' + rel)};`)
  );

  const content = [
    '// auto-generated by tex4npm stage — do not edit',
    ...jsImports,
    ...cssImports,
    '',
  ].join('\n');

  await writeFile(path.join(tex4npmDir, 'bundle-entry.js'), content);
}

// Try symlink first (fast, live-edit friendly), fall back to hard link
// (no elevated privileges on Windows), then plain copy (cross-drive).
async function linkWithFallback(src, dest) {
  try {
    await symlink(src, dest);
  } catch (e) {
    if (e.code !== 'EPERM') throw e;
    try {
      await link(src, dest);
    } catch {
      await copyFile(src, dest);
    }
  }
}
