import { readFile, writeFile, mkdir, rm, symlink, link, copyFile } from 'fs/promises';
import glob from 'fast-glob';
import path from 'path';

// Run all three pre-build stages. Returns the list of discovered latex packages.
export async function stage(config) {
  const packages = await findLatexPackages(config.configDir);
  await populateTexmf(config.tex4npmTexmf, packages);
  await generateBundleEntry(config.tex4npmDir, packages);
  return packages;
}

// Stage 1: scan node_modules for packages with a "latex" field.
// Only checks top-level and scoped packages, not deeply nested ones.
export async function findLatexPackages(root) {
  const manifests = await glob(
    ['node_modules/*/package.json', 'node_modules/@*/*/package.json'],
    { cwd: root, absolute: true }
  );

  const packages = [];
  for (const manifestPath of manifests) {
    let pkg;
    try {
      pkg = JSON.parse(await readFile(manifestPath, 'utf8'));
    } catch {
      continue;
    }
    if (!pkg.latex) continue;
    // "postprocess" and "xourse" may each be a single relative path or an
    // array; normalize to arrays. postprocess hooks are loaded and run by
    // postprocess.js (Phase 4, D5); xourse hooks are loaded and run by
    // xourse.js during materialize.
    const rawPost = pkg.latex.postprocess;
    const postprocess = Array.isArray(rawPost) ? rawPost : (rawPost ? [rawPost] : []);
    const rawXourse = pkg.latex.xourse;
    const xourse = Array.isArray(rawXourse) ? rawXourse : (rawXourse ? [rawXourse] : []);
    packages.push({
      name: pkg.name,
      dir: path.dirname(manifestPath),
      sty: pkg.latex.sty ?? [],
      fourht: pkg.latex['4ht'] ?? [],
      cls: pkg.latex.cls ?? [],
      cfg: pkg.latex.cfg ?? [],
      css: pkg.latex.css ?? [],
      hasJs: Boolean(pkg.main ?? pkg.exports ?? pkg.module),
      postprocess,
      xourse,
    });
  }

  return packages;
}

// Stage 2: wipe .tex4npm/texmf/tex/latex/ and repopulate with links to
// TeX assets (.sty, .4ht, .cls, .cfg). Throws on filename collision.
export async function populateTexmf(tex4npmTexmf, packages) {
  const latexDir = path.join(tex4npmTexmf, 'tex', 'latex');
  await rm(latexDir, { recursive: true, force: true });
  await mkdir(latexDir, { recursive: true });

  const seen = new Map(); // basename → package name

  for (const pkg of packages) {
    for (const rel of [...pkg.sty, ...pkg.fourht, ...pkg.cls, ...pkg.cfg]) {
      const src = path.resolve(pkg.dir, rel);
      const basename = path.basename(rel);

      if (seen.has(basename)) {
        throw new Error(
          `latex filename collision: ${basename} is declared by both ` +
          `${seen.get(basename)} and ${pkg.name}`
        );
      }
      seen.set(basename, pkg.name);

      await linkWithFallback(src, path.join(latexDir, basename));
    }
  }
}

// Stage 3: write .tex4npm/bundle-entry.js importing all ximera package JS and CSS.
export async function generateBundleEntry(tex4npmDir, packages) {
  await mkdir(tex4npmDir, { recursive: true });

  const jsImports = packages
    .filter(p => p.hasJs !== false)
    .map(p => `import ${JSON.stringify(p.name)};`);
  const cssImports = packages.flatMap(p =>
    p.css.map(rel => `import ${JSON.stringify(p.name + '/' + rel)};`)
  );

  const content = [
    '// auto-generated by tex4npm stage — do not edit',
    ...jsImports,
    ...cssImports,
    '',
  ].join('\n');

  await writeFile(path.join(tex4npmDir, 'bundle-entry.js'), content);
}

// Try symlink first (fast, live-edit friendly), fall back to hard link
// (no elevated privileges on Windows), then plain copy (cross-drive).
async function linkWithFallback(src, dest) {
  try {
    await symlink(src, dest);
  } catch (e) {
    if (e.code !== 'EPERM') throw e;
    try {
      await link(src, dest);
    } catch {
      await copyFile(src, dest);
    }
  }
}
