import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm } from 'fs/promises';
import os from 'os';
import path from 'path';
import { watch } from './watch.js';

const WITH_DOC = '\\begin{document}hello\\end{document}';

// Wait for a condition to become true, polling every 50ms up to timeoutMs.
async function waitFor(condition, timeoutMs = 5000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await condition()) return;
    await new Promise(r => setTimeout(r, 50));
  }
  throw new Error('waitFor timed out');
}

describe('watch', () => {
  let root, outDir, config;

  before(async () => {
    root = await mkdtemp(path.join(os.tmpdir(), 'tex4npm-watch-'));
    outDir = path.join(root, 'dist');
    await mkdir(outDir, { recursive: true });
    await mkdir(path.join(root, '.tex4npm'), { recursive: true });

    // Write a minimal bundle-entry.js so stage/bundle don't fail
    await writeFile(path.join(root, '.tex4npm', 'bundle-entry.js'),
      '// auto-generated by tex4npm stage — do not edit\n');

    await writeFile(path.join(root, 'main.tex'), WITH_DOC);

    config = {
      root,
      outDir,
      tex4npmDir: path.join(root, '.tex4npm'),
      tex4npmTexmf: path.join(root, '.tex4npm', 'texmf'),
      workers: 1,
      passes: 2,
      clean: true,
      exclude: [],
    };
  });

  after(() => rm(root, { recursive: true, force: true }));

  it('triggers an initial build on start', async () => {
    const builds = [];
    const buildFn = async (files) => { builds.push([...files]); };

    const handle = watch(config, buildFn);
    try {
      await waitFor(() => builds.length > 0);
      assert.ok(builds[0].some(f => f.endsWith('main.tex')));
    } finally {
      await handle.close();
    }
  });

  it('triggers a rebuild when a .tex file changes', async () => {
    const builds = [];
    const buildFn = async (files) => {
      // Simulate writing the output so the file is no longer dirty
      for (const f of files) {
        const out = path.join(outDir, path.relative(root, f).replace('.tex', '.html'));
        await writeFile(out, '<html><head></head><body>ok</body></html>');
      }
      builds.push([...files]);
    };

    const handle = watch(config, buildFn);
    try {
      // Wait for initial build
      await waitFor(() => builds.length >= 1);
      const beforeCount = builds.length;

      // Modify the file to trigger a rebuild
      await writeFile(path.join(root, 'main.tex'), WITH_DOC + '\n% changed');
      await waitFor(() => builds.length > beforeCount);
      assert.ok(builds.at(-1).some(f => f.endsWith('main.tex')));
    } finally {
      await handle.close();
    }
  });

  it('returns a close handle that stops the watcher', async () => {
    const builds = [];
    const handle = watch(config, async (files) => { builds.push(files); });
    await waitFor(() => builds.length > 0);
    await handle.close();
    const countAfterClose = builds.length;

    // Modify file after closing — should not trigger another build
    await writeFile(path.join(root, 'main.tex'), WITH_DOC + '\n% after close');
    await new Promise(r => setTimeout(r, 200));
    assert.equal(builds.length, countAfterClose);
  });
});
